# -*- coding: utf-8 -*-
"""Rede_Bayesiana_Credito.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uGoNBTNJzzx3n4-JsizuwSQdFNuNiFyG
"""

!pip install pgmpy kagglehub -q

import kagglehub
import os

# Download do dataset
path = kagglehub.dataset_download("parisrohan/credit-score-classification")
print("Path to dataset files:", path)

# Listar arquivos disponíveis
for f in os.listdir(path):
    print(f)

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Carregar o arquivo para treino
df = pd.read_csv(os.path.join(path, 'train.csv'))
print(f"Shape original: {df.shape}")
df.head(3)

# Selecionar as 10 variáveis da rede bayesiana
colunas = [
    'Age', 'Annual_Income', 'Num_Bank_Accounts', 'Num_Credit_Card',
    'Interest_Rate', 'Num_of_Loan', 'Delay_from_due_date',
    'Outstanding_Debt', 'Credit_Mix', 'Credit_Score'
]

df = df[colunas].copy()

# Limpeza: remover caracteres inválidos e converter para numérico
def limpar_numerico(serie):
    serie = serie.astype(str).str.replace(r'[^0-9.\-]', '', regex=True)
    serie = pd.to_numeric(serie, errors='coerce')
    return serie

for col in ['Age', 'Annual_Income', 'Num_Bank_Accounts', 'Num_Credit_Card',
            'Interest_Rate', 'Num_of_Loan', 'Delay_from_due_date', 'Outstanding_Debt']:
    df[col] = limpar_numerico(df[col])

# Limpar Credit_Mix
df['Credit_Mix'] = df['Credit_Mix'].astype(str).str.strip()
df['Credit_Mix'] = df['Credit_Mix'].replace({'_': np.nan})

# Remover linhas com valores inválidos / negativos absurdos
df = df[df['Age'].between(18, 100)]
df = df[df['Annual_Income'] > 0]
df = df[df['Num_of_Loan'].between(0, 20)]
df = df[df['Delay_from_due_date'].between(0, 365)]
df = df[df['Outstanding_Debt'] >= 0]
df = df[df['Num_Bank_Accounts'].between(0, 20)]
df = df[df['Num_Credit_Card'].between(0, 15)]
df = df[df['Interest_Rate'].between(1, 100)]

# Remover linhas com NaN
df = df.dropna()

print(f"Shape após limpeza: {df.shape}")
print("\nDistribuição do Credit_Score:")
print(df['Credit_Score'].value_counts())

df_disc = pd.DataFrame()

# Age
df_disc['Age'] = pd.cut(df['Age'], bins=[0, 30, 50, 100],
                         labels=['Jovem', 'Adulto', 'Senior'])

# Income
df_disc['Income'] = pd.cut(df['Annual_Income'],
                            bins=[0, 30000, 80000, float('inf')],
                            labels=['Baixa', 'Media', 'Alta'])

# Num_Bank_Accounts
df_disc['Num_Bank_Accounts'] = pd.cut(df['Num_Bank_Accounts'],
                                       bins=[-1, 3, 20],
                                       labels=['Poucos', 'Varios'])

# Num_Credit_Card
df_disc['Num_Credit_Card'] = pd.cut(df['Num_Credit_Card'],
                                     bins=[-1, 3, 15],
                                     labels=['Poucos', 'Varios'])

# Interest_Rate
df_disc['Interest_Rate'] = pd.cut(df['Interest_Rate'],
                                   bins=[0, 10, 20, 100],
                                   labels=['Baixa', 'Media', 'Alta'])

# Num_of_Loan
df_disc['Num_of_Loan'] = pd.cut(df['Num_of_Loan'],
                                  bins=[-1, 3, 20],
                                  labels=['Poucos', 'Varios'])

# Delay_from_due_date
df_disc['Delay_from_due_date'] = pd.cut(df['Delay_from_due_date'],
                                          bins=[-1, 5, 15, 365],
                                          labels=['Sem_atraso', 'Moderado', 'Grave'])

# Outstanding_Debt
df_disc['Outstanding_Debt'] = pd.cut(df['Outstanding_Debt'],
                                      bins=[-1, 500, 2000, float('inf')],
                                      labels=['Baixa', 'Media', 'Alta'])

# Credit_Mix
df_disc['Credit_Mix'] = df['Credit_Mix'].astype(str)

# Credit_Score
df_disc['Credit_Score'] = df['Credit_Score'].astype(str)

df_disc = df_disc.astype(str)
df_disc = df_disc.replace('nan', np.nan).dropna()

print(f"Shape final discretizado: {df_disc.shape}")
print("\nExemplo:")
df_disc.head(3)

"""*texto em itálico*"""

from pgmpy.models import DiscreteBayesianNetwork
from pgmpy.estimators import MaximumLikelihoodEstimator
from pgmpy.inference import VariableElimination

# Estrutura da rede
estrutura = [
    ('Age',               'Credit_Score'),
    ('Income',            'Outstanding_Debt'),
    ('Income',            'Credit_Score'),
    ('Num_Bank_Accounts', 'Credit_Score'),
    ('Num_Credit_Card',   'Outstanding_Debt'),
    ('Num_Credit_Card',   'Credit_Mix'),
    ('Interest_Rate',     'Outstanding_Debt'),
    ('Num_of_Loan',       'Outstanding_Debt'),
    ('Num_of_Loan',       'Delay_from_due_date'),
    ('Delay_from_due_date', 'Credit_Score'),
    ('Outstanding_Debt',  'Credit_Score'),
    ('Credit_Mix',        'Credit_Score'),
]

modelo = DiscreteBayesianNetwork(estrutura)
print("Estrutura da Rede Bayesiana criada com sucesso!")
print(f"   Nós: {modelo.nodes()}")
print(f"   Arestas: {len(modelo.edges())}")

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import networkx as nx

G = nx.DiGraph(estrutura)

# Layout
pos = {
    'Age':               (-2, 2),
    'Income':            (-1, 3),
    'Num_Bank_Accounts': (0, 2),
    'Num_Credit_Card':   (1, 3),
    'Interest_Rate':     (2, 3),
    'Num_of_Loan':       (3, 2),
    'Delay_from_due_date': (2, 0),
    'Outstanding_Debt':  (1, 0),
    'Credit_Mix':        (-1, 0),
    'Credit_Score':      (0, -2),
}

# Cores dos nós
cor_nos = []
for n in G.nodes():
    if n == 'Credit_Score':
        cor_nos.append('#01696f')  # alvo
    elif n in ['Outstanding_Debt', 'Delay_from_due_date', 'Credit_Mix']:
        cor_nos.append('#4f98a3')  # intermediário
    else:
        cor_nos.append('#cedcd8')  # entrada

fig, ax = plt.subplots(figsize=(14, 10))
nx.draw_networkx(
    G, pos=pos, ax=ax,
    node_color=cor_nos,
    node_size=3500,
    font_size=9,
    font_weight='bold',
    arrows=True,
    arrowsize=20,
    edge_color='#555',
    width=2,
    connectionstyle='arc3,rad=0.05'
)

# Legenda
legenda = [
    mpatches.Patch(color='#cedcd8', label='Variáveis de Entrada'),
    mpatches.Patch(color='#4f98a3', label='Variáveis Intermediárias'),
    mpatches.Patch(color='#01696f', label='Variável Alvo (Credit_Score)'),
]
ax.legend(handles=legenda, loc='lower right', fontsize=10)
ax.set_title('Rede Bayesiana — Classificação de Score de Crédito', fontsize=14, fontweight='bold')
ax.axis('off')
plt.tight_layout()
plt.savefig('rede_bayesiana.png', dpi=150, bbox_inches='tight')
plt.show()
print("Gráfico salvo como 'rede_bayesiana.png'")

modelo.fit(
    df_disc,
    estimator=MaximumLikelihoodEstimator
)
print("CPDs estimados com sucesso!")
print(f"   Total de CPDs: {len(modelo.cpds)}")

# Verifica validade do modelo
valido = modelo.check_model()
print(f"Modelo válido: {valido}")

# Exibir a CPD da variável alvo
print("=" * 60)
print("CPD de Credit_Score:")
print("=" * 60)
print(modelo.get_cpds('Credit_Score'))

# Exibir CPD de algumas variáveis intermediárias
for var in ['Outstanding_Debt', 'Credit_Mix', 'Delay_from_due_date']:
    print(f"\nCPD de {var}:")
    print(modelo.get_cpds(var))

inferencia = VariableElimination(modelo)

# Consulta 1: Perfil de risco alto
print("=" * 65)
print("CONSULTA 1 — Perfil de Risco Alto")
print("  Age=Jovem, Income=Baixa, Num_of_Loan=Varios, Delay=Grave")
print("=" * 65)

resultado1 = inferencia.query(
    variables=['Credit_Score'],
    evidence={
        'Age': 'Jovem',
        'Income': 'Baixa',
        'Num_of_Loan': 'Varios',
        'Delay_from_due_date': 'Grave'
    }
)
print(resultado1)

# Consulta 2: Perfil de baixo risco
print("=" * 65)
print("CONSULTA 2 — Perfil de Baixo Risco")
print("  Age=Adulto, Income=Alta, Num_of_Loan=Poucos, Delay=Sem_atraso")
print("=" * 65)

resultado2 = inferencia.query(
    variables=['Credit_Score'],
    evidence={
        'Age': 'Adulto',
        'Income': 'Alta',
        'Num_of_Loan': 'Poucos',
        'Delay_from_due_date': 'Sem_atraso'
    }
)
print(resultado2)

# Consulta 3: Inferência sobre Credit_Mix dado Income
print("=" * 65)
print("CONSULTA 3 — Credit_Mix dado Income=Alta e Num_Credit_Card=Varios")
print("=" * 65)

resultado3 = inferencia.query(
    variables=['Credit_Mix'],
    evidence={
        'Income': 'Alta',
        'Num_Credit_Card': 'Varios'
    }
)
print(resultado3)

# Consulta 4: Inferência sobre Outstanding_Debt
print("=" * 65)
print("CONSULTA 4 — Outstanding_Debt dado Income=Baixa, Num_of_Loan=Varios")
print("=" * 65)

resultado4 = inferencia.query(
    variables=['Outstanding_Debt'],
    evidence={
        'Income': 'Baixa',
        'Num_of_Loan': 'Varios'
    }
)
print(resultado4)

# Consulta 5: Score dado Credit_Mix=Good e Dívida Baixa
print("=" * 65)
print("CONSULTA 5 — Credit_Score dado Credit_Mix=Good, Outstanding_Debt=Baixa")
print("=" * 65)

resultado5 = inferencia.query(
    variables=['Credit_Score'],
    evidence={
        'Credit_Mix': 'Good',
        'Outstanding_Debt': 'Baixa'
    }
)
print(resultado5)

import matplotlib.pyplot as plt
import numpy as np

fig, axes = plt.subplots(1, 3, figsize=(15, 5))
fig.suptitle('Inferências Probabilísticas — Credit_Score', fontsize=14, fontweight='bold')

consultas = [
    (resultado1, 'Perfil de Risco Alto\n(Jovem, Renda Baixa, Atrasos Graves)'),
    (resultado2, 'Perfil de Baixo Risco\n(Adulto, Renda Alta, Sem Atrasos)'),
    (resultado5, 'Credit_Mix=Good\nDívida Baixa'),
]

cores_score = {'Good': '#01696f', 'Standard': '#4f98a3', 'Poor': '#a12c7b'}

for ax, (res, titulo) in zip(axes, consultas):
    estados = res.state_names['Credit_Score']
    valores = [res.values[res.state_names['Credit_Score'].index(s)] for s in estados]
    cores = [cores_score.get(s, '#888') for s in estados]
    bars = ax.bar(estados, valores, color=cores, edgecolor='white', linewidth=1.5)
    for bar, val in zip(bars, valores):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
                f'{val:.2%}', ha='center', va='bottom', fontsize=10, fontweight='bold')
    ax.set_ylim(0, 1)
    ax.set_ylabel('Probabilidade')
    ax.set_title(titulo, fontsize=10)
    ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda y, _: f'{y:.0%}'))
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

plt.tight_layout()
plt.savefig('inferencias_credit_score.png', dpi=150, bbox_inches='tight')
plt.show()
print("Gráfico salvo como 'inferencias_credit_score.png'")

# Probabilidade marginal do Credit_Score (sem evidências)
print("=" * 50)
print("Probabilidade Marginal de Credit_Score")
print("(sem nenhuma evidência)")
print("=" * 50)

marginal = inferencia.query(variables=['Credit_Score'])
print(marginal)

# Impacto do atraso no Credit_Score
print("\n" + "=" * 50)
print("Impacto do Delay_from_due_date no Credit_Score")
print("=" * 50)

for delay in ['Sem_atraso', 'Moderado', 'Grave']:
    res = inferencia.query(
        variables=['Credit_Score'],
        evidence={'Delay_from_due_date': delay}
    )
    estados = res.state_names['Credit_Score']
    print(f"\nDelay={delay}:")
    for s in estados:
        val = res.values[estados.index(s)]
        print(f"  P(Credit_Score={s}) = {val:.4f} ({val:.1%})")

# Verificar independências condicionais na rede
print("Independências Locais do Modelo:")
print("=" * 50)

nos = list(modelo.nodes())
independencias = modelo.local_independencies(nos)
for ind in independencias.independencies:
    print(" ", ind)